# fly.toml app configuration file generated for vibed-render-worker on 2026-05-25T16:19:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vibed-render-worker'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = "shared-cpu-2x"
  memory = "4096"
  cpus = 2
